### ISSUE TITLE
Imports and path

### ISSUE THREAD

**Issue by jolual2747** [cristian-rincon/api-movies#1]
Hi, how you doing?

![issue](https://github.com/cristian-rincon/api-movies/assets/111621047/b86430ec-00fa-4079-ac09-2935d2a1f511)

I have a doubt respect to main.py. I see you import like ```from app.routers.v1.users import router as users_router``` and I also see your __init__.py files. But I'm wondering if you modified the PYTHONPATH enviroment variable and why this is not present on the .Dockerfile?

I hope you can answer so I can solve my doubt.

Thanks in advance!

**Comment by cristian-rincon** [comment]
Hi @jolual2747, the app/ folder is a Python module, that's why we can import using this name as the base path. (E.g. from app.something import somethingelse)

Also, there's no need to change the PYTHONPATH in this app. Do you need it for an specific use case?

**Comment by jolual2747** [comment]
Oh, got it. Perfect and thx for your help!
